### ISSUE TITLE
Gadil's dialogue tree seems entirely broken

### ISSUE THREAD

**Issue by ALIENQuake** [BiGWorldProject/FishingForTrouble#10]
> Also Gadil's dialogue tree seems entirely broken. Every state is entirely separate and all use the same trigger. I don't think this is how Gadil's dialogue looked last time I played this; he gave me some sort of quest to get the cup, and now I can't get it at all (though I have the cup and he still asks me if I want it).

From: http://www.shsforums.net/topic/61020-fishing-for-trouble-current-version/#entry610681

**Comment by TotoR115** [comment]
@ALIENQuake 

should be now solved

**Comment by ALIENQuake** [comment]
Solved by [1aaf8bc](https://github.com/InfinityMods/FishingForTrouble/commit/1aaf8bcbcfb50eafe5a5e7ca4683d28d915b502e)
