### ISSUE TITLE
An Assertion failed in CCGameEffect.cpp at line number 1536 (Area YS0350)

### ISSUE THREAD

**Issue by ALIENQuake** [BiGWorldProject/FishingForTrouble#13]
> yschdg.cre has an invalid effect in BG2 / ToB (326). It is probably only available in the EE versions. (Solution: Remove via "Edit" in NI.)
> Tt still seems to be the same in the latest version.

http://www.shsforums.net/topic/56638-mod-bugs/page-6#entry611607

@TotoR115 What should be the general approach to such problems? Remove effect for classic BG2? Is there a way to find out which particular thing is causing the crash?

**Comment by TotoR115** [comment]
Strange that I miss this opcode. 

This opcode (326: Apply Effects List) is EE only but parameters for it are not correctly Set and ressource is not a spell: RNDTRE02.spl does not exists. I have look deeper and it seems to be a wrong bit insert in the creature file.

To be simple, I think, as there is already a equiped item `RNDTRE02`, that this effect should be simply removed for all version of the game.
