### ISSUE TITLE
Issues from SHS

### ISSUE THREAD

**Issue by TotoR115** [BiGWorldProject/FishingForTrouble#16]
> 1. The innkeeper in the village of Port-whatsitsname - once restored - when asks about his daughter's piano, talks about Duke Eltan of Athkalta. Except Athkalta - and the rest of Amn, presently, are ruled by the Council of Six. 
> 2. Finding the door for the guy with the key to the lighthouse was tricky and I went by it many times
> 3. The dialog with Demons when Edwin was in the party but was not in the lighthouse area stumped me, until I eventually checked the Deamon's .dlg file for clues. 
> 4. Initially I just ran by the traps(speed) of the dead and got the key.  I also wanted to try the potions, but when one of my party NPCs used it, he still could not get by the traps.  Does it need to be the main character?
> 5. Caravan forces never went hostile no matter what dialog options.  I could steal the lotus without hostile.   The lotus would not burn unless caravan forces were dead.  They died one by one without going hostile.
> 6. After getting Gelterath to restore Porthpentyrch, Gelterath and the other two could not be found before a week (near boats) or after (in Blue Harpy).  Porthpentyrch was corretly replaced with the restored village version.  I suppose I could have used CluaCreateCreature or foiund the correct global to tweak, but forum information made me realize the quest was basically done....so I just left things there.  I read that the only thing after that would be to find Elminister in the Den of Seven vales and he was not there, either.
> (http://www.shsforums.net/topic/56638-mod-bugs/?p=585715)

> 7. I killed the Tanarr'i. Yeah. Why? He's an evil demon that says he's trapped. When you kill demons, they return to their home plane. Apparently that is also the case for him. Resolving nicely the Tanarr'i questline. Except of course, the mod doesn't make him respawn, and doesn't expect you at all to kill him.
http://www.shsforums.net/topic/56638-mod-bugs/?p=606841

**Comment by TotoR115** [comment]
- The innkeeper in the village of Port-whatsitsname - once restored - when asks about his daughter's piano, talks about Duke Eltan of Athkalta. Except Athkalta - and the rest of Amn, presently, are ruled by the Council of Six.
- Finding the door for the guy with the key to the lighthouse was tricky and I went by it many times
- The dialog with Demons when Edwin was in the party but was not in the lighthouse area stumped me, until I eventually checked the Deamon's .dlg file for clues.
- Caravan forces never went hostile no matter what dialog options. 
- I could steal the lotus without hostile. The lotus would not burn unless caravan forces were dead.

- I killed the Tanarr'i. Yeah. Why? He's an evil demon that says he's trapped. When you kill demons, they return to their home plane. Apparently that is also the case for him. Resolving nicely the Tanarr'i questline. Except of course, the mod doesn't make him respawn, and doesn't expect you at all to kill him.

All fixed in #17

- After getting Gelterath to restore Porthpentyrch, Gelterath and the other two could not be found before a week (near boats) or after (in Blue Harpy). Porthpentyrch was corretly replaced with the restored village version. I suppose I could have used CluaCreateCreature or foiund the correct global to tweak, but forum information made me realize the quest was basically done....so I just left things there. 

fixed in #11 and #18

last one:
- Initially I just ran by the traps(speed) of the dead and got the key. I also wanted to try the potions, but when one of my party NPCs used it, he still could not get by the traps. Does it need to be the main character? #18
- I read that the only thing after that would be to find Elminister in the Den of Seven vales and he was not there, either. #18
-  Cerendor Hold: Nallia ells the caravan master that her mother would reward him. Trouble is, Nallia's mother is long dead, now her father is dead also, leaving only her aunty, who currently isn't talking to her. #18

Not an issue:
- Background information about how corruptive it is and maybe a decent street value?  Good parties would destroy it and evil would sell it. --> you can burn it or give it for money to Chief Inspector Brega in Council of the six
- In fact, being as I play a fighter and did that whole fighter stronghold quest, I guess that makes my character the boss in those parts, no? Yet, nobody acknowledges that. a bunch of people actually asked how come I was even allowed on the top floor of the keep. --> player fighter is ruller of a keep not a noble family, so been not known is acceptable
- The town restoration path could also have an evil option where you fight Geltherath or tell him you are done and keeping the orb. --> may be an insteressant idea

**Comment by ALIENQuake** [comment]
@TotoR115 Ready for new release?

**Comment by TotoR115** [comment]
One more PR: I am not found of the trigger use for ghoul transformation and I would like to restore ghoul portrait for Player 1 if possible.

**Comment by ALIENQuake** [comment]
Sure!
Regarding Ghoul, I've done some investigation here: http://www.shsforums.net/topic/60774-help-needed-lets-finally-nail-ghoul-potion-bug/

**Comment by ALIENQuake** [comment]
@ALIENQuake Sure!
Regarding Ghoul, I've done some investigation here: http://www.shsforums.net/topic/60774-help-needed-lets-finally-nail-ghoul-potion-bug/

**Comment by TotoR115** [comment]
@ALIENQuake 
I have taken a look to this post of yours, and the actual potions work like your "bad" items.

It works like this:
- yspotn01 curse you for a short period of time (600) and after a spell is launch (ysghoul.spl) that transforming you in ghoul by removing all your items and creating an item in the glove slots. the item change race, class, portrait and add some immunities

- if you use yspotn02 before the end of the timer (600) it protect you from the spell and the transformation. It does not change you back if you already transform in a ghoul.

- If you are a ghoul, you can always speak with Elminster to change you back

issues with that:

- the item (ysghoul1) is placed in glove slots. That allows you to equipe yourself with every weapons (ie polymorph object) and magical weapons. I have changed that in the last commit, and now the spell (like spells for magic weapons) create it as a magical weapon undispellable that prevent from equipping other weapons.

- the portrait change seems a nice idea, but I have removed it, because on oBG2 it is a one way changed; it is not really a problem in fact for Player1 as you can always changed it in customize tab. However, for other NPC it is not possible... As the other can drink the potion, it is way too broken for regular players. I will try to reintroduce it by other means.

The "good" items that you point in your first post tranform you directly in ghoul and remove direcly the transformation.
Lastly for the explosion, I have no issues with those actual potions, I can't reproduce this bug.

**Comment by ALIENQuake** [comment]
Thank you very much for your support! I will release updated version in the upcoming days.
