### ISSUE TITLE
Issue due to case sensitiveness (BWFISHW.d / bwfishw.d)

### ISSUE THREAD

**Issue by Frenzgyn** [BiGWorldProject/FishingForTrouble#20]
The "old" BWFISHW.d should be deleted, since it is not replaced by the updated "bwfishw.d", potentially generating issue on Windows systems.

**Comment by ALIENQuake** [comment]
@Frenzgyn Nice catch, resolved by [6893291](https://github.com/InfinityMods/FishingForTrouble/commit/6893291a71452029465911135aaf6cbed9568518)
